version: '3.9'
x-subscription_command: &subscription_command |
  mix deps.get
  ./wait-for pg:5432 -- mix ecto.setup
  mix phx.server
services:
  subscription:
    restart: always
    image: "${COMPOSE_PROJECT_NAME}_subscription_${MIX_ENV:-dev}"
    build:
      dockerfile: Dockerfile.development
    command:
      - 'sh'
      - '-c'
      - *subscription_command
    environment:
      # phoenix
      MIX_ENV: "${MIX_ENV:-dev}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-top_secret}"
      # telegram
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      # pg
      POSTGRES_PASSWORD: subscription
      POSTGRES_DB: subscription_development
      POSTGRES_USER: subscription
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_POOL: 10
    networks:
      - net
    ports:
      - '4000:4000'
    depends_on:
      - pg
    volumes:
      - .:/subscription
      - subscription_deps:/subscription/deps
      - subscription_build_data:/subscription/_build
  pg:
    restart: always
    image: postgres:14.0-alpine
    command:
      - 'postgres'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=1000'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: subscription
      POSTGRES_DB: subscription_development
      POSTGRES_USER: subscription
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_POOL: 10
      PGDATA: /var/lib/postgresql/data
    networks:
      - net
networks:
  net:
volumes:
  subscription_deps:
  subscription_build_data:
  pg_data:
